name: r-environment
channels:
  - conda-forge
dependencies:
  - r-base=4.4.2
  - r-remotes=2.5.0
  - r-curl=6.0.1
  - r-sf=1.0_19
  - r-rgbif=3.8.3
  - r-rvertnet=0.8.4
  - r-terra
  - gdal
  - proj
  - proj-data
  - geos
